.github/pull_request_template.md

feat: Create pull request template

---

.github/workflows/ci-lint-and-jest.yml

JIRA issue: [FSU-38](https://klau.atlassian.net/browse/FSU-38)
Create CI Github Action file to make sure that eslint and jest don't fail after push a commit.
Every time you push changes to your GitHub branch or make PR, GitHub actions will be run to check that the changes we've made won't cause errors. (run Eslint and Jest)

feat fsu-38 add ci-lint-and-jest github action file

---

README.md

- No JIRA issue - 
This PR is just an update of our existing README file.

docs: update main readme file

---

packages/design-system/__mocks__/svg.js
packages/design-system/components/icon/Icon.jsx
packages/design-system/components/icon/__tests__/Icon.test.jsx
packages/design-system/jest.config.js

This PR introduces the SVG mock for jest testing. It also adds a basic icon test to make sure the mock handles it.

feat: add icon mock & icon basic test

---

packages/design-system/.storybook/main.js
packages/design-system/theme/__stories__/Theme.stories.mdx

JIRA issue: [FSU-80](https://klau.atlassian.net/browse/FSU-80)
Added missing path to theme to stories.

fix: theme gallery added to stories

---

packages/design-system/.storybook/styles.css
packages/design-system/icons/__stories__/Icons.stories.mdx

JIRA issue: [FSU-74](https://klau.atlassian.net/browse/FSU-74)
I changed gallery display to grid and adjust the rest of styles to this new "grid" situation :) .  
I also removed the div added on FSU-33, because it changed the position of the icon name (previously the name was under the icon, and adding the div made it next to the icon).

chore: improve icons gallery grid

---

.github/workflows/pr-name.yml

JIRA issue: [FSU-XX](https://klau.atlassian.net/browse/FSU-XX)

wrong PR name test

---

packages/frontend/app/next.config.js
packages/frontend/app/package.json
packages/frontend/app/pages/index.jsx
yarn.lock

This PR adds the svgr package to `frontend` directory to handle svg icons as React component (the same way it's done in the Storybook).

feat(frontend): introduce svgr package; add example icon to index

---

packages/design-system/components/iconButton/__stories__/IconButton.stories.mdx
packages/design-system/components/iconButton/__tests__/IconButton.test.jsx

Add missing aria-label prop to IconButton test to get rid off error after running test.

fix: add aria-label to icon button test

---

packages/design-system/icons/ArrowUp.svg

fix: replace arrow up svg icon
No Jira issue, just Paulina's perfect eye 😅 
This PR replaces the ArrowUp icon with a new, corrected svg.
You can compare the current one with the new one:
- [Current staging](https://sterczace-uszy-ds.vercel.app/?path=/story/icons--page)
- [This PR's staging]()

fix: replace arrow up svg icon

---

packages/design-system/blocks/navigation/Navigation.jsx
packages/design-system/blocks/navigation/Navigation.styled.js
packages/design-system/blocks/navigation/__stories__/Navigation.stories.mdx
packages/design-system/blocks/navigation/data.js
packages/design-system/blocks/navigation/index.js
packages/design-system/components/button/Button.jsx
packages/design-system/components/button/Button.styled.js

feat: navigation
JIRA issue: [FSU-29](https://klau.atlassian.net/browse/FSU-29)
This PR introduces the Navigation (without dropdowns).
The code is ready to review, however the background color can change in the future.

feat: navigation

---

packages/design-system/components/title/Title.jsx
packages/design-system/components/title/Title.styled.js
packages/design-system/components/title/__stories__/Ttitle.stories.mdx
packages/design-system/components/typography/Typography.jsx

JIRA issue: [FSU-123](https://klau.atlassian.net/browse/FSU-123)

feat: update title sizes

---

packages/design-system/patterns/card/Card.jsx
packages/design-system/patterns/card/Card.styled.js
packages/design-system/patterns/card/__stories__/Card.stories.mdx

feat(card): add responsive layout
JIRA issue: [FSU-91](https://klau.atlassian.net/browse/FSU-91)
This PR introduces the responsive Card's layout.

feat(card): add responsive layout

---

packages/frontend/app/pages/index.jsx
packages/frontend/app/templates/HomePage/HomePage.jsx
packages/frontend/app/templates/HomePage/index.js
packages/frontend/app/templates/HomePage/types.js

JIRA issue: [FSU-177](https://klau.atlassian.net/browse/FSU-117)

feat(home): page setup

---

packages/design-system/patterns/ctaBanner/CtaBanner.jsx
packages/design-system/patterns/ctaBanner/CtaBanner.styled.js
packages/design-system/patterns/ctaBanner/__stories__/CtaBanner.stories.mdx
packages/design-system/patterns/ctaBanner/__tests__/CtaBanner.test.jsx
packages/design-system/patterns/ctaBanner/index.js

feat(design-system): create the CTA Banner component
JIRA issue: [FSU-150](https://klau.atlassian.net/browse/FSU-150)
This PR introduces the CTA Banner component that will be used on `v1` pages soon.

feat(): create the CTA Banner component

---

packages/frontend/app/templates/Contact/components/Form/Form.jsx

I changed the options in the form to start with capital letters, it looks cleaner now :)

fix: capitalize form options

---

packages/frontend/app/pages/do-adopcji.jsx
packages/frontend/app/templates/Adoption/Adoption.jsx
packages/frontend/app/templates/Adoption/Adoption.styled.js
packages/frontend/app/templates/Adoption/index.js

JIRA issue: [FSU-165](https://klau.atlassian.net/browse/FSU-165)
This PR introduces basic Next.js setup for a new "For adoption" page.
Link to the page:  [For adoption page](https://sterczaceuszy-git-fsu-165-for-adoption-setup-fsu.vercel.app/do-adopcji)

feat: create for-adoption page setup

---

packages/design-system/patterns/animalCard/AnimalCard.jsx
packages/design-system/patterns/animalCard/__tests__/AnimalCard.test.jsx
packages/frontend/app/lib/queries.js
packages/frontend/app/lib/types.js
packages/frontend/app/package.json
packages/frontend/app/pages/do-adopcji/[slug].jsx
packages/frontend/app/pages/do-adopcji/index.jsx
packages/frontend/app/templates/Animal/Animal.jsx
packages/frontend/app/templates/Animal/Animal.styled.js
packages/frontend/app/templates/Animal/index.js
yarn.lock

JIRA issue: [FSU-167](https://klau.atlassian.net/browse/FSU-167)
This PR introduces a basic setup for a single animal page. Each animal is available at: `/do-adopcji/[slug]` now.
Verify if the single page works by clicking any animal card on the home page.

feat(single-animal): page setup

---

packages/design-system/blocks/footer/Footer.jsx
packages/design-system/blocks/footer/Footer.styled.js

JIRA issue: [FSU-245](https://klau.atlassian.net/browse/FSU-245)
Footer update to v2
- [] New and existing unit tests pass locally with my changes.

feat: footer v2 

---

packages/frontend/app/lib/gtag.js
packages/frontend/app/pages/_app.jsx

JIRA issue: [FSU-289](https://klau.atlassian.net/browse/FSU-289)
Add Google Analytics 4 tracking code
https://enlear.academy/add-google-analytics-to-a-next-js-application-5525892844db
https://dev.to/collegewap/how-to-add-google-analytics-to-nextjs-app-52f7

feat: add Google Analytics 4 tracking code

---

packages/frontend/app/templates/Adoption/components/VirtualAdoption/VirtualAdoption.jsx
packages/frontend/app/templates/Animal/components/MoreInfo/MoreInfo.jsx

JIRA issue: [FSU-285](https://klau.atlassian.net/browse/FSU-285)
This PR updates the second button on the single animal page to redirect users to the virtual adoption.

feat: update button to link to the virtual adoption

---

packages/frontend/app/templates/About/components/AboutUs/AboutUs.jsx
packages/frontend/app/templates/About/components/Achievements/Achievements.jsx
packages/frontend/app/templates/About/components/Supporters/Supporters.jsx
packages/frontend/app/templates/About/components/Values/Values.jsx
packages/frontend/e2e/cypress/e2e/about.cy.js

JIRA issue: [FSU-213](https://klau.atlassian.net/browse/FSU-213)
This PR adds basic E2E tests to the About page. It also fixes some accessibility issues found by Cypress.

test(about-page): add basic e2e tests

---

packages/design-system/components/input/Input.styled.js
packages/design-system/components/select/Select.styled.js
packages/design-system/components/textarea/Textarea.styled.js

JIRA issue: [FSU-106](https://klau.atlassian.net/browse/FSU-106)
This PR updates focus styles in the: input, textarea and select components.
The focus effect is now aligned with other interactive elements.

feat: update focus states

---

.github/workflows/e2e.yml
packages/frontend/app/next.config.js
packages/frontend/app/package.json
packages/frontend/app/pages/_app.jsx
packages/frontend/e2e/cypress.config.js
packages/frontend/e2e/package.json
yarn.lock

This PR adds Hotjar init to the app.
JIRA issue: [FSU-326](https://klau.atlassian.net/browse/FSU-326)
https://medium.com/@romansorin/using-hotjar-and-google-analytics-with-next-js-to-track-behavior-a2283d659767
Make sure the page still works - [Home](https://sterczaceuszy-git-fsu-326-hotjar-init-sterczace-uszy.vercel.app/)

feat: init hotjar

---

.github/workflows/e2e.yml
packages/design-system/blocks/navigation/Navigation.styled.js
packages/frontend/app/templates/Animal/components/Gallery/Gallery.styled.js
packages/frontend/e2e/cypress.config.js

Repaired stroke in the dog image and sticky position navigation bar.
JIRA issues: [FSU-287](https://klau.atlassian.net/browse/FSU-287),   [FSU-336](https://klau.atlassian.net/browse/FSU-336)

fix: repair stroke in dog image and add sticky position navigation bar

---

packages/design-system/components/checkbox/Checkbox.jsx
packages/design-system/components/errorMessage/ErrorMessage.jsx
packages/design-system/components/errorMessage/ErrorMessage.mdx
packages/design-system/components/errorMessage/ErrorMessage.stories.jsx
packages/design-system/components/errorMessage/__tests__/Input.test.jsx
packages/design-system/components/errorMessage/index.js
packages/design-system/components/input/Input.jsx
packages/design-system/components/textarea/Textarea.jsx

Extracted error message from Input, Textarea and Checkbox components and created reusable ErrorMessage component.
JIRA issue: [FSU-298](https://klau.atlassian.net/browse/FSU-298)

feat: extract inputs error message

---

packages/frontend/app/pages/zasady-adopcji.jsx
packages/frontend/app/templates/AdoptionRules/AdoptionRules.jsx
packages/frontend/app/templates/AdoptionRules/AdoptionRules.styled.js
packages/frontend/app/templates/AdoptionRules/components/AdoptionSteps/AdoptionRules.styled.js
packages/frontend/app/templates/AdoptionRules/components/AdoptionSteps/AdoptionSteps.jsx
packages/frontend/app/templates/AdoptionRules/components/AdoptionSteps/AdoptionSteps.styled.js
packages/frontend/app/templates/AdoptionRules/components/AdoptionSteps/index.js
packages/frontend/app/templates/AdoptionRules/components/Hero/Hero.jsx
packages/frontend/app/templates/AdoptionRules/components/Hero/Hero.styled.js
packages/frontend/app/templates/AdoptionRules/components/Hero/index.js
packages/frontend/app/templates/AdoptionRules/index.js

JIRA issue: [FSU-374](https://klau.atlassian.net/browse/FSU-374)
- [AdoptionRules](https://sterczaceuszy-git-fsu-374-adoption-rules-page-sterczace-uszy.vercel.app/zasady-adopcji)

feat: add adoption rules page

---

packages/frontend/e2e/cypress/e2e/financial-data.cy.js

This PR adds e2e tests for FinancialData page
JIRA issue: [FSU-409](https://klau.atlassian.net/browse/FSU-409)

feat: add e2e tests for FinancialData page

---

.github/workflows/e2e.yml

JIRA issue: [FSU-XXX](https://klau.atlassian.net/browse/FSU-XXX)

chore: update e2e.yml

---

.github/workflows/pr-name.yml

JIRA issue: [FSU-XXX](https://klau.atlassian.net/browse/FSU-XXX)

fix: use fixed version of commitlint

---

packages/frontend/app/templates/Documents/Documents.jsx
packages/frontend/app/templates/Documents/components/DocumentsList/DocumentsList.jsx
packages/frontend/app/templates/Documents/components/DocumentsList/DocumentsList.styled.js
packages/frontend/app/templates/FreeSupport/components/Fanimani/Fanimani.jsx
packages/shared/data/index.js

This PR adds Google form links on the Surveys page.
JIRA issue: [FSU-416](https://klau.atlassian.net/browse/FSU-416)
[Ankiety](https://sterczaceuszy-git-fsu-416-add-google-form-links-non-profit-dev.vercel.app/ankiety)

chore: add Google form links

---

.github/workflows/e2e.yml
packages/frontend/e2e/cypress.config.js

JIRA issue: [FSU-XXX](https://klau.atlassian.net/browse/FSU-XXX)

fix: update e2e.yml
